/**
 * CrashLens Core Constants
 * Extracted from app/index.html — COL, EPDO_WEIGHTS, EPDO_PRESETS, STATE_EPDO_WEIGHTS
 */
window.CL = window.CL || {};
CL.core = CL.core || {};

CL.core.constants = {
    COL: {
        ID: 'Document Nbr', YEAR: 'Crash Year', DATE: 'Crash Date', TIME: 'Crash Military Time',
        SEVERITY: 'Crash Severity', K: 'K_People', A: 'A_People', B: 'B_People', C: 'C_People',
        COLLISION: 'Collision Type', WEATHER: 'Weather Condition', LIGHT: 'Light Condition',
        SURFACE: 'Roadway Surface Condition', ALIGNMENT: 'Roadway Alignment',
        ROAD_DESC: 'Roadway Description', INT_TYPE: 'Intersection Type',
        TRAFFIC_CTRL: 'Traffic Control Type', CTRL_STATUS: 'Traffic Control Status',
        WORKZONE: 'Work Zone Related', SCHOOL: 'School Zone',
        ALCOHOL: 'Alcohol?', BIKE: 'Bike?', PED: 'Pedestrian?', SPEED: 'Speed?',
        DISTRACTED: 'Distracted?', DROWSY: 'Drowsy?', HITRUN: 'Hitrun?',
        SENIOR: 'Senior?', YOUNG: 'Young?', NIGHT: 'Night?',
        UNRESTRAINED: 'Unrestrained?', MOTORCYCLE: 'Motorcycle?',
        FUNC_CLASS: 'Functional Class', AREA_TYPE: 'Area Type',
        ROUTE: 'RTE Name', NODE: 'Node', MP: 'RNS MP',
        X: 'x', Y: 'y',
        // Jurisdiction field (Column BC in Virginia crash data)
        JURISDICTION: 'Physical Juris Name',
        // Additional road properties from data dictionary
        FACILITY_TYPE: 'Facility Type',
        ROAD_SYSTEM: 'SYSTEM',
        OWNERSHIP: 'Ownership',
        NODE_OFFSET: 'Node Offset',
        // Extended fields for detailed crash analysis
        DRUG: 'Drug Related?',
        GUARDRAIL: 'Guardrail Related?',
        LGTRUCK: 'Lgtruck?',
        ROAD_DEPARTURE: 'RoadDeparture Type',
        MAX_SPEED_DIFF: 'Max Speed Diff',
        FIRST_HARMFUL: 'First Harmful Event',
        FIRST_HARMFUL_LOC: 'First Harmful Event Loc',
        ROAD_DEFECT: 'Roadway Defect',
        RELATION_TO_ROAD: 'Relation To Roadway',
        ANIMAL: 'Animal Related?',
        // Standard unused columns - now utilized
        VEHICLE_COUNT: 'Vehicle Count',
        PERSONS_INJURED: 'Persons Injured',
        PED_KILLED: 'Pedestrians Killed',
        PED_INJURED: 'Pedestrians Injured'
    },

    EPDO_WEIGHTS_DEFAULT: { K: 462, A: 62, B: 12, C: 5, O: 1 },

    EPDO_PRESETS: {
        hsm2010:  { name: 'HSM Standard (2010)', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 },
                    description: 'Highway Safety Manual standard weights (AASHTO/FHWA)' },
        vdot2024: { name: 'VDOT 2024', weights: { K: 1032, A: 53, B: 16, C: 10, O: 1 },
                    description: 'Derived from VDOT 2024 crash cost ratios ($12.8M K / $12.4K O)' },
        fhwa2022: { name: 'FHWA 2022', weights: { K: 975, A: 48, B: 13, C: 8, O: 1 },
                    description: 'Derived from FHWA 2022 crash cost ratios ($11.6M K / $11.9K O)' },
        custom:   { name: 'Custom', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 },
                    description: 'User-defined custom weights' },
        stateDefault: { name: 'State Default (Auto)', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 },
                    description: 'Automatically uses recommended EPDO weights for the selected state',
                    isAuto: true }
    },

    STATE_EPDO_WEIGHTS: {
        // --- States with published/derived EPDO weights ---
        '51': { name: 'Virginia (VDOT 2025)', weights: { K: 1032, A: 53, B: 16, C: 10, O: 1 },
                source: 'VDOT 2024 crash cost memo ($12.8M K / $12.4K O)' },
        '06': { name: 'California (Caltrans 2023)', weights: { K: 1100, A: 58, B: 17, C: 11, O: 1 },
                source: 'Caltrans TASAS methodology, adjusted for CA cost of living' },
        '48': { name: 'Texas (TxDOT 2023)', weights: { K: 920, A: 55, B: 14, C: 9, O: 1 },
                source: 'TxDOT crash cost data via AASHTOWare Safety' },
        '12': { name: 'Florida (FDOT 2023)', weights: { K: 985, A: 50, B: 15, C: 9, O: 1 },
                source: 'FDOT Safety Office HSIP crash cost estimates' },
        '36': { name: 'New York (NYSDOT 2023)', weights: { K: 1050, A: 55, B: 15, C: 10, O: 1 },
                source: 'NYSDOT Safety Analysis System crash costs' },
        '17': { name: 'Illinois (IDOT 2023)', weights: { K: 850, A: 45, B: 10, C: 5, O: 1 },
                source: 'IDOT crash cost ratios for HSIP analysis' },
        '37': { name: 'North Carolina (NCDOT 2023)', weights: { K: 770, A: 77, B: 8, C: 8, O: 1 },
                source: 'NCDOT HSIP severity methodology (elevated A weight)' },
        '42': { name: 'Pennsylvania (PennDOT 2023)', weights: { K: 975, A: 48, B: 13, C: 8, O: 1 },
                source: 'PennDOT uses FHWA 2022 national baseline' },
        '39': { name: 'Ohio (ODOT 2023)', weights: { K: 975, A: 48, B: 13, C: 8, O: 1 },
                source: 'ODOT uses FHWA 2022 national baseline' },
        '13': { name: 'Georgia (GDOT 2023)', weights: { K: 975, A: 48, B: 13, C: 8, O: 1 },
                source: 'GDOT AASHTO Safety / Numetric crash cost integration' },
        '25': { name: 'Massachusetts (MassDOT 2024)', weights: { K: 1200, A: 60, B: 18, C: 12, O: 1 },
                source: 'MassDOT 2024 crash costs ($19.4M K / $16.2K O)' },
        '34': { name: 'New Jersey (NJDOT 2023)', weights: { K: 1050, A: 55, B: 15, C: 10, O: 1 },
                source: 'NJDOT crash cost analysis (high cost of living adjustment)' },
        '53': { name: 'Washington (WSDOT 2023)', weights: { K: 975, A: 48, B: 13, C: 8, O: 1 },
                source: 'WSDOT uses FHWA 2022 national baseline' },
        '04': { name: 'Arizona (ADOT 2023)', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 },
                source: 'ADOT uses HSM Standard (2010)' },
        '26': { name: 'Michigan (MDOT 2023)', weights: { K: 975, A: 48, B: 13, C: 8, O: 1 },
                source: 'MDOT uses FHWA 2022 national baseline' },
        '49': { name: 'Utah (UDOT 2024)', weights: { K: 975, A: 48, B: 13, C: 8, O: 1 },
                source: 'UDOT annual crash cost update (FHWA methodology)' },
        '41': { name: 'Oregon (ODOT 2023)', weights: { K: 975, A: 48, B: 13, C: 8, O: 1 },
                source: 'Oregon DOT uses FHWA 2022 national baseline' },
        '22': { name: 'Louisiana (LaDOTD 2023)', weights: { K: 975, A: 48, B: 13, C: 8, O: 1 },
                source: 'LaDOTD uses FHWA crash cost methodology' },
        '35': { name: 'New Mexico (NMDOT 2023)', weights: { K: 567, A: 33, B: 33, C: 33, O: 1 },
                source: 'NMDOT uses simplified injury categories' },
        '56': { name: 'Wyoming (WYDOT 2023)', weights: { K: 975, A: 48, B: 13, C: 8, O: 1 },
                source: 'WYDOT uses FHWA national baseline' },
        '09': { name: 'Connecticut (CTDOT 2023)', weights: { K: 1050, A: 55, B: 15, C: 10, O: 1 },
                source: 'CTDOT crash cost analysis (high cost of living)' },
        // --- States using HSM Standard (2010) as default ---
        '01': { name: 'Alabama', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '02': { name: 'Alaska', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '05': { name: 'Arkansas', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '08': { name: 'Colorado (CDOT)', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '10': { name: 'Delaware', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '11': { name: 'District of Columbia', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '15': { name: 'Hawaii', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '16': { name: 'Idaho', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '18': { name: 'Indiana', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '19': { name: 'Iowa', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '20': { name: 'Kansas', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '21': { name: 'Kentucky', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '23': { name: 'Maine', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '24': { name: 'Maryland', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '27': { name: 'Minnesota', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '28': { name: 'Mississippi', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '29': { name: 'Missouri', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '30': { name: 'Montana', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '31': { name: 'Nebraska', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '32': { name: 'Nevada', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '33': { name: 'New Hampshire', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '38': { name: 'North Dakota', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '40': { name: 'Oklahoma', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '44': { name: 'Rhode Island', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '45': { name: 'South Carolina', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '46': { name: 'South Dakota', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '47': { name: 'Tennessee', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '50': { name: 'Vermont', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '54': { name: 'West Virginia', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        '55': { name: 'Wisconsin', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 }, source: 'HSM Standard (2010)' },
        // --- Default fallback (for any FIPS not listed) ---
        '_default': { name: 'HSM Standard (2010)', weights: { K: 462, A: 62, B: 12, C: 5, O: 1 },
                      source: 'Highway Safety Manual standard EPDO weights' }
    }
};

CL._registerModule('core/constants');
